### ISSUE TITLE
Error updating score: Unknown column 'final' in 'field list'

### ISSUE THREAD

**Issue by jimmz86** [rbiddle/phppickem#2]
When i try to update the score i get this error:
Error updating score: Unknown column 'final' in 'field list'

i used 
[2021-schedule-V1-3.sql.txt](https://github.com/rbiddle/phppickem/files/7149311/2021-schedule-V1-3.sql.txt)

from https://github.com/rothkj1022/phppickem/issues/50

to get the schedule for 2021

**Comment by jimmz86** [comment]
i think i solved it.

The colum final was missing in nflp_schedule.
Created it and it seeeeems to work ...

**Comment by rbiddle** [comment]
A few more changes have been made to that table since go live. The current install script is maintained for them, but I'm not planning any upgrade scripts to automate the updates since the changes are pretty simple schema updates and can be fixed by re-installing between seasons. If anyone needs/wants help making the update without re-installing, message me or join the discord and I'd be happy to help out.
